import { chromium } from 'playwright';
import { startServer } from '/work/nds/tools/serve.js';
import fs from 'fs';
const s = await startServer();
const b = await chromium.launch({ args: ['--use-gl=swiftshader', '--no-sandbox'] });
const p = await b.newPage({ viewport: { width: 900, height: 1400 } });
await p.goto(s.url + (process.env.SC==='1'?'':'?scale=4'), { waitUntil: 'networkidle' });
await p.waitForFunction('window.DSi && window.DSi.ready');
await p.evaluate(() => { window.DSi.skipBoot(); const a = window.DSi.openSettings(); a.confirmExit = { t: 60, sel: -1 }; window.__A = a; });
await p.waitForTimeout(400);
await p.evaluate(() => { window.__A.confirmExit = { t: 60, sel: -1 }; window.DSi.drawSettings(); });
await p.waitForTimeout(50);
const png = await p.evaluate(() => document.getElementById('bottom').toDataURL('image/png'));
fs.writeFileSync('/tmp/exitdlg.png', Buffer.from(png.split(',')[1], 'base64'));
await b.close(); s.close(); console.log('ok');
