import { chromium } from 'playwright';
import { startServer } from '/work/nds/tools/serve.js';
import fs from 'fs';
const s = await startServer();
const b = await chromium.launch({ args: ['--use-gl=swiftshader', '--no-sandbox'] });
const p = await b.newPage({ viewport: { width: 900, height: 1400 } });
await p.goto(s.url + '?scale=4', { waitUntil: 'networkidle' });
await p.waitForFunction('window.DSi && window.DSi.ready');
await p.evaluate(() => { window.__demoTime = Date.parse('2000-01-01T09:30:00'); window.DSi.skipBoot(); const a = window.DSi.openSettings(); a.page = 0; a.sub = null; });
await p.waitForTimeout(400);
await p.evaluate(() => window.DSi.drawSettings());
await p.waitForTimeout(50);
const png = await p.evaluate(() => document.getElementById('top').toDataURL('image/png'));
fs.writeFileSync('/tmp/settop_scale4.png', Buffer.from(png.split(',')[1], 'base64'));
await b.close(); s.close(); console.log('ok');
